require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CountryPicturesController do

  # This should return the minimal set of attributes required to create a valid
  # CountryPicture. As you add validations to CountryPicture, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CountryPicturesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all country_pictures as @country_pictures" do
      country_picture = CountryPicture.create! valid_attributes
      get :index, {}, valid_session
      assigns(:country_pictures).should eq([country_picture])
    end
  end

  describe "GET show" do
    it "assigns the requested country_picture as @country_picture" do
      country_picture = CountryPicture.create! valid_attributes
      get :show, {:id => country_picture.to_param}, valid_session
      assigns(:country_picture).should eq(country_picture)
    end
  end

  describe "GET new" do
    it "assigns a new country_picture as @country_picture" do
      get :new, {}, valid_session
      assigns(:country_picture).should be_a_new(CountryPicture)
    end
  end

  describe "GET edit" do
    it "assigns the requested country_picture as @country_picture" do
      country_picture = CountryPicture.create! valid_attributes
      get :edit, {:id => country_picture.to_param}, valid_session
      assigns(:country_picture).should eq(country_picture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CountryPicture" do
        expect {
          post :create, {:country_picture => valid_attributes}, valid_session
        }.to change(CountryPicture, :count).by(1)
      end

      it "assigns a newly created country_picture as @country_picture" do
        post :create, {:country_picture => valid_attributes}, valid_session
        assigns(:country_picture).should be_a(CountryPicture)
        assigns(:country_picture).should be_persisted
      end

      it "redirects to the created country_picture" do
        post :create, {:country_picture => valid_attributes}, valid_session
        response.should redirect_to(CountryPicture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved country_picture as @country_picture" do
        # Trigger the behavior that occurs when invalid params are submitted
        CountryPicture.any_instance.stub(:save).and_return(false)
        post :create, {:country_picture => {}}, valid_session
        assigns(:country_picture).should be_a_new(CountryPicture)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CountryPicture.any_instance.stub(:save).and_return(false)
        post :create, {:country_picture => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested country_picture" do
        country_picture = CountryPicture.create! valid_attributes
        # Assuming there are no other country_pictures in the database, this
        # specifies that the CountryPicture created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CountryPicture.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => country_picture.to_param, :country_picture => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested country_picture as @country_picture" do
        country_picture = CountryPicture.create! valid_attributes
        put :update, {:id => country_picture.to_param, :country_picture => valid_attributes}, valid_session
        assigns(:country_picture).should eq(country_picture)
      end

      it "redirects to the country_picture" do
        country_picture = CountryPicture.create! valid_attributes
        put :update, {:id => country_picture.to_param, :country_picture => valid_attributes}, valid_session
        response.should redirect_to(country_picture)
      end
    end

    describe "with invalid params" do
      it "assigns the country_picture as @country_picture" do
        country_picture = CountryPicture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CountryPicture.any_instance.stub(:save).and_return(false)
        put :update, {:id => country_picture.to_param, :country_picture => {}}, valid_session
        assigns(:country_picture).should eq(country_picture)
      end

      it "re-renders the 'edit' template" do
        country_picture = CountryPicture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CountryPicture.any_instance.stub(:save).and_return(false)
        put :update, {:id => country_picture.to_param, :country_picture => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested country_picture" do
      country_picture = CountryPicture.create! valid_attributes
      expect {
        delete :destroy, {:id => country_picture.to_param}, valid_session
      }.to change(CountryPicture, :count).by(-1)
    end

    it "redirects to the country_pictures list" do
      country_picture = CountryPicture.create! valid_attributes
      delete :destroy, {:id => country_picture.to_param}, valid_session
      response.should redirect_to(country_pictures_url)
    end
  end

end
