require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TestimoniesController do

  # This should return the minimal set of attributes required to create a valid
  # Testimony. As you add validations to Testimony, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TestimoniesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all testimonies as @testimonies" do
      testimony = Testimony.create! valid_attributes
      get :index, {}, valid_session
      assigns(:testimonies).should eq([testimony])
    end
  end

  describe "GET show" do
    it "assigns the requested testimony as @testimony" do
      testimony = Testimony.create! valid_attributes
      get :show, {:id => testimony.to_param}, valid_session
      assigns(:testimony).should eq(testimony)
    end
  end

  describe "GET new" do
    it "assigns a new testimony as @testimony" do
      get :new, {}, valid_session
      assigns(:testimony).should be_a_new(Testimony)
    end
  end

  describe "GET edit" do
    it "assigns the requested testimony as @testimony" do
      testimony = Testimony.create! valid_attributes
      get :edit, {:id => testimony.to_param}, valid_session
      assigns(:testimony).should eq(testimony)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Testimony" do
        expect {
          post :create, {:testimony => valid_attributes}, valid_session
        }.to change(Testimony, :count).by(1)
      end

      it "assigns a newly created testimony as @testimony" do
        post :create, {:testimony => valid_attributes}, valid_session
        assigns(:testimony).should be_a(Testimony)
        assigns(:testimony).should be_persisted
      end

      it "redirects to the created testimony" do
        post :create, {:testimony => valid_attributes}, valid_session
        response.should redirect_to(Testimony.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved testimony as @testimony" do
        # Trigger the behavior that occurs when invalid params are submitted
        Testimony.any_instance.stub(:save).and_return(false)
        post :create, {:testimony => {}}, valid_session
        assigns(:testimony).should be_a_new(Testimony)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Testimony.any_instance.stub(:save).and_return(false)
        post :create, {:testimony => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested testimony" do
        testimony = Testimony.create! valid_attributes
        # Assuming there are no other testimonies in the database, this
        # specifies that the Testimony created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Testimony.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => testimony.to_param, :testimony => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested testimony as @testimony" do
        testimony = Testimony.create! valid_attributes
        put :update, {:id => testimony.to_param, :testimony => valid_attributes}, valid_session
        assigns(:testimony).should eq(testimony)
      end

      it "redirects to the testimony" do
        testimony = Testimony.create! valid_attributes
        put :update, {:id => testimony.to_param, :testimony => valid_attributes}, valid_session
        response.should redirect_to(testimony)
      end
    end

    describe "with invalid params" do
      it "assigns the testimony as @testimony" do
        testimony = Testimony.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Testimony.any_instance.stub(:save).and_return(false)
        put :update, {:id => testimony.to_param, :testimony => {}}, valid_session
        assigns(:testimony).should eq(testimony)
      end

      it "re-renders the 'edit' template" do
        testimony = Testimony.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Testimony.any_instance.stub(:save).and_return(false)
        put :update, {:id => testimony.to_param, :testimony => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested testimony" do
      testimony = Testimony.create! valid_attributes
      expect {
        delete :destroy, {:id => testimony.to_param}, valid_session
      }.to change(Testimony, :count).by(-1)
    end

    it "redirects to the testimonies list" do
      testimony = Testimony.create! valid_attributes
      delete :destroy, {:id => testimony.to_param}, valid_session
      response.should redirect_to(testimonies_url)
    end
  end

end
